<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>{{ $title }} Export</title>
    <style>
        @page {
            margin: 0.8cm;
            size: auto;
        }

        body {
            font-family: 'DejaVu Sans', 'Helvetica', 'Arial', sans-serif;
            font-size: 9px;
            line-height: 1.15;
            color: #333;
            background-color: #fff;
            margin: 0;
            padding: 0;
        }

        .container {
            padding: 10px;
        }

        .report-header {
            position: relative;
            height: 50px;
            padding-bottom: 10px;
            margin-bottom: 12px;
            border-bottom: 2px solid #000;
        }



        .header-text {
            position: absolute;
            top: 0;
            left: 0px;
            right: 0;
        }

        .title {
            font-size: 18px;
            font-weight: 700;
            color: #2c3e50;
            margin-bottom: 3px;
            letter-spacing: -0.3px;
        }

        .subtitle {
            font-size: 10px;
            color: #7f8c8d;
            font-style: italic;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 12px;
            font-size: 8px;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
        }

        thead {
            display: table-header-group;
        }

        th {
            background-color: #a2a3a4;
            color: #2c3e50;
            font-weight: bold;
            text-align: left;
            padding: 5px 4px;
            border-bottom: 1.5px solid #000;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
        }

        td {
            padding: 4px;
            border-bottom: 0.5px solid #e8e8e8;
            vertical-align: top;
        }

        /* Alternate row styling */
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        /* Conditional formatting for cells */
        .success {
            color: #27ae60;
        }

        .warning {
            color: #f39c12;
        }

        .danger {
            color: #e74c3c;
        }

        /* Formatting for numeric columns */
        .numeric {
            text-align: right;
            font-family: 'DejaVu Sans Mono', monospace;
        }

        /* Column-specific widths */
        .col-id {
            width: 5%;
        }

        .col-date {
            width: 10%;
        }

        .col-status {
            width: 8%;
        }

        .col-desc {
            width: auto;
        }

        /* Summary section */
        .summary {
            margin-top: 10px;
            margin-bottom: 15px;
            padding: 8px;
            background-color: #f8f9fa;
            border-left: 3px solid #000;
            font-size: 9px;
        }

        .summary-title {
            font-weight: bold;
            margin-bottom: 4px;
        }

        .summary-content {
            color: #555;
        }

        .footer {
            margin-top: 15px;
            padding-top: 8px;
            border-top: 1px solid #ddd;
            display: flex;
            justify-content: space-between;
            font-size: 8px;
            color: #95a5a6;
        }

        .footer-left {
            text-align: left;
        }

        .footer-right {
            text-align: right;
        }

        .page-number:before {
            content: "Page " counter(page) " of " counter(pages);
        }

        /* Table layout optimization for many columns */
        @media print {
            table {
                table-layout: fixed;
            }

            th,
            td {
                word-break: break-word;
                overflow-wrap: break-word;
            }

            thead {
                display: table-header-group;
            }

            tfoot {
                display: table-footer-group;
            }
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="report-header">
            <div class="header-text">
                <div class="title">{{ $title }}</div>
                <div class="subtitle">Data exported on {{ date('F j, Y \a\t h:i A') }}</div>
            </div>
        </div>

        <div class="summary">
            <div class="summary-title">Export Summary</div>
            <div class="summary-content">
                Total records: {{ count($rows) }} |
                Generated by: {{ auth()->user()->name ?? 'System' }} |
            </div>
        </div>

        <table>
            <thead>
                <tr>
                    @foreach ($headers as $index => $header)
                        <th class="col-{{ Str::slug($header) }}">{{ $header }}</th>
                    @endforeach
                </tr>
            </thead>
            <tbody>
                @forelse ($rows as $row)
                    <tr>
                        @foreach ($row as $index => $cell)
                            <td
                                class="{{ is_numeric($cell) && !in_array($headers[$index] ?? '', ['ID', 'Code']) ? 'numeric' : '' }}">
                                {{ $cell }}
                            </td>
                        @endforeach
                    </tr>
                @empty
                    <tr>
                        <td colspan="{{ count($headers) }}" style="text-align: center; padding: 20px;">
                            No data available for this report.
                        </td>
                    </tr>
                @endforelse
            </tbody>
        </table>

        <div class="footer">
            <div class="footer-left">
                {{ $title }} | Confidential - For internal use only
            </div>
            <div class="footer-right page-number"></div>
        </div>
    </div>
</body>

</html>
